mission:
  # the initial_mission that should be accomplished
  name: "square_corridor_navigation"
  goals:
    acceptance_criterion:
      tolerance: 0.01
    robots:
      uav1:
        states:
          - [-15, -15, 10]
          - [15, -15, 10]
          - [15, 15, 10]
          - [-15, 15, 10]
      uav2:
        states:
          - [-10, -10, 10]
          - [10, -10, 10]
          - [10, 10, 10]
          - [-10, 10, 10]

unit:
  distance: "meter"
  time: "second"
ros:
  bag:
    dir: "/home/donkarlo/Dropbox/projs/research/data/self-aware-drones/ctumrs/two-drones/"
gazebo:
  world:
    dir: "/home/donkarlo/Dropbox/projs/research/artificial-intelligence/self-awareness/selfaware-drones/rosws/worlds.yaml/"

members:
  normal:
    name: "normal"
    robots:
      uav1: #leader
        plan:
          actions:
            # same role with similar goal talerance. just states change
            type: "homogeneous"
            name: "goto"
            goals:
              acceptance_criterion:
                  tolerance: 0.01
              states:
                name: "position"
                file:
                  path: "/home/donkarlo/mrs_workspace/src/trajectory_loader/sample_trajectories/rectangle_30_0.5.txt"
                  vector_sep: "\n"
                  vector_components_sep: " "
                width: 30
                sampling_interval: 0.5
      uav2:
        plan:
          actions:
            # same role with similar goal talerance. just states change
            type: "homogeneous"
            name: "goto"
            goals:
              acceptance_criterion:
                tolerance: 0.01
              states:
                name: "position"
                file:
                  path: "/home/donkarlo/mrs_workspace/src/trajectory_loader/sample_trajectories/rectangle_10_0.5.txt"
                  vector_sep: "\n"
                  vector_components_sep: " "
                width: 10
                sampling_interval: 0.5

    ros:
      bag:
        dir: "normal-scenario/"
        file_name: "uav1_odometry_odom_gps_rplidar_scan.yaml"
        robots:
          uav1:
            file:
              name: "uav1_odometry_odom_gps_rplidar_scan.yaml"
            sensor:
              odom_gps:
                msg_count: 434065
              rp_a2:
                msg_count: 86901
          uav2:
            file:
              name: "uav2_odometry_odom_gps_rplidar_scan.yaml"
            sensor:
              odom_gps:
                msg_count: 434059
              rp_a2:
                msg_count: 86902
    world: "hollow_nested_cubes"

  follow:
    topic_data_dir: "follow-scenario/"
    world: "hollow_nested_cubes_narrows_on_one_side"

  next_to:
    topic_data_dir: "next-to-scenario/"