shared:
  gazebo:
    dir: "/home/donkarlo/Dropbox/projs/research/artificial-intelligence/self-awareness/selfaware-drones/rosws/worlds.schema.yaml/"
worlds:
  hollow_nested_cubes:
    id: "hollow_nested_cubes"
    obstacles:
      shape:
        name: "hollow_nested_cubes"
        height: 7.5
        thickness: 0.05
      square:
        inner:
          length: 8
        outer:
          length: 32
    gazebo:
      world:
        file: "normal-scenario.world"
  hollow_nested_cubes_narrows_on_one_side:
    id: "hollow_nested_cubes_narrowed_on_a_side"
    obstacles:
      shape:
        name: "hollow_nested_cubes_narrowed_on_a_side"
        height: 7.5
        thickness: 0.05
      square:
        inner:
          length: 8
        outer:
          length: 32
    gazebo:
      world:
        file: "follow-scenario.world"
